name: Deploy API

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build Docker image
        run: |
          docker build -t 404fra/plutomierz-api ./api

      - name: Log in to DockerHub
        run: echo ${{ secrets.DOCKERHUB_TOKEN }} | docker login -u 404fra --password-stdin

      - name: Push Docker image
        run: docker push 404fra/plutomierz-api:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.VPS_SSH_KEY }}

      - name: Deploy to VPS
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa ${{ secrets.SSH_HOST }} << 'EOF'
            docker pull 404fra/plutomierz-api:latest
            docker stop plutomierz-api || true
            docker rm plutomierz-api || true
            docker run -d --name plutomierz-api --restart always -p 3000:3000 404fra/plutomierz-api:latest
          EOF