name: Deploy API

on:
  push:
    branches:
      - master
    paths:
      - 'api/**'
      - '.github/workflows/deploy-api.yml'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to DockerHub
        run: echo ${{ secrets.DOCKERHUB_TOKEN }} | docker login -u 404fra --password-stdin

      - name: Build and push Docker image
        run: |
          docker-compose -f ./api/docker-compose.yml build
          docker-compose -f ./api/docker-compose.yml push

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.VPS_SSH_KEY }}

      - name: Deploy to VPS
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" | tr -d '\r' > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa ${{ secrets.SSH_HOST }} << 'EOF'
            cd /path/to/your/project
            docker-compose down
            docker-compose pull
            docker-compose up -d
          EOF